# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

before:
  hooks:
    - go mod tidy

project_name: pinata

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
  description: GitHub Actions pinner.
  full_description: |-
    Make your GitHub Actions usage more secure by pinning them to their SHA's.
  homepage: https://github.com/caarlos0/pinata
  license: MIT
  maintainers:
    - Carlos Alexandro Becker <carlos@becker.software>

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - go_first_class

homebrew_casks:
  - repository:
      owner: caarlos0
      name: homebrew-tap
    url:
      verified: github.com/caarlos0/pinata
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pinata"]
          end

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    section: utils

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

checksum:
  name_template: "checksums.txt"
